"use client";

import { useState, Suspense } from "react";
import { useSearchParams } from "next/navigation";
import Navbar from "../components/Navbar";
import { DOCS_FALLBACK } from "../../lib/constants";

// ── Hardcoded README ───────────────────────────────────────────────────────
const HARDCODED_README = `# authController.js — Session Documentation

**Generated by CodeCouncil AI** · Feb 28, 2026

---

## Overview

This module handles authentication for the application using Supabase. A critical memory leak was identified and resolved during the debugging session.

## Bug Report

| Field | Details |
|-------|---------|
| **Issue** | Memory leak in \`fetchUser\` |
| **Severity** | Critical |
| **Introduced** | Snapshot v2 (10:43 AM) |
| **Fixed** | Snapshot v5 (11:15 AM) |
| **Assigned** | @arjun, @priya |

## Root Cause

An uncleared \`setInterval\` in \`fetchUser\` was accumulating session references in memory on every call, causing heap exhaustion under concurrent load.

\`\`\`js
// ❌ Buggy version
export async function fetchUser(userId) {
  const sessions = [];
  // memory leak — interval never cleared
  setInterval(() => {
    sessions.push(supabase.auth.getSession());
  }, 1000);
  // ...
}
\`\`\`

## Fix Applied

\`\`\`js
// ✅ Fixed version
export async function fetchUser(userId) {
  const { data, error } = await supabase
    .from('users')
    .select('*')
    .eq('id', userId)
    .single();
  if (error) throw error;
  return data;
}
\`\`\`

## API Reference

### \`fetchUser(userId: string): Promise<User>\`

Fetches a single user record from the \`users\` table.

**Parameters**
- \`userId\` — The UUID of the user to fetch.

**Returns** — A \`User\` object or throws on error.

**Example**
\`\`\`js
const user = await fetchUser("abc-123");
console.log(user.email);
\`\`\`

---

### \`handleLogin(e: FormEvent): Promise<void>\`

Handles OTP login form submission.

**Side Effects**
- Sets \`loading\` state during request.
- Sends OTP email via \`supabase.auth.signInWithOtp\`.
- Guards against state updates after unmount via \`mounted\` ref.

---

## Timeline Summary

| Snapshot | Time | Description |
|----------|------|-------------|
| v1 | 10:00 AM | Clean initial code |
| v2 | 10:43 AM | Bug introduced (memory leak) |
| v3 | 10:51 AM | Team debugging session |
| v4 | 11:05 AM | Fix attempted |
| v5 | 11:15 AM | Fixed & verified ✓ |

## Team

- **Arjun** — Identified loop issue
- **Priya** — Spotted typo on line 42
- **You** — Applied the final fix
- **CodeCouncil AI** — Detected memory leak, suggested refactor

---

*Generated automatically by CodeCouncil · Debug smarter, ship faster.*
`;

// ── Left panel info ────────────────────────────────────────────────────────
const SNAPSHOTS_INFO = [
  { label: "v1 · Clean", color: "#3B82F6", time: "10:00 AM" },
  { label: "v2 · Bug", color: "#EF4444", time: "10:43 AM" },
  { label: "v3 · Debug", color: "#F59E0B", time: "10:51 AM" },
  { label: "v4 · Patch", color: "#A855F7", time: "11:05 AM" },
  { label: "v5 · Fixed ✓", color: "#10B981", time: "11:15 AM" },
];

// ── Inner component (needs useSearchParams) ────────────────────────────────
function DocPageInner() {
  const searchParams = useSearchParams();
  const fromHackathon = searchParams.get("from") === "hackathon";

  const [generating, setGenerating] = useState(false);
  const [readme, setReadme] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);

  const handleGenerate = async () => {
    setGenerating(true);
    setReadme(null);
    try {
      const res = await fetch("/api/ai/docs", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ projectName: "CodeCouncil", messages: [], code: "" }),
      });
      const data = await res.json();
      setReadme(data.markdown ?? DOCS_FALLBACK);
    } catch {
      setReadme(DOCS_FALLBACK);
    } finally {
      setGenerating(false);
    }
  };

  const handleCopy = async () => {
    await navigator.clipboard.writeText(readme ?? "");
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleExport = () => {
    const blob = new Blob([readme ?? ""], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url; a.download = "README.md"; a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div style={{ display: "flex", flex: 1, overflow: "hidden", minHeight: 0 }}>

      {/* ── LEFT: Branded panel ── */}
      <div style={{
        width: 280, flexShrink: 0,
        background: "linear-gradient(160deg, #0D0D1F 0%, #111124 50%, #0A0A18 100%)",
        borderRight: "1px solid #1E1E32",
        display: "flex", flexDirection: "column",
        alignItems: "center", justifyContent: "center",
        padding: "40px 28px", gap: 0,
        position: "relative", overflow: "hidden",
      }}>
        {/* subtle grid bg */}
        <div style={{ position: "absolute", inset: 0, backgroundImage: "linear-gradient(rgba(59,130,246,0.03) 1px, transparent 1px), linear-gradient(90deg, rgba(59,130,246,0.03) 1px, transparent 1px)", backgroundSize: "32px 32px", pointerEvents: "none" }} />

        {/* Logo block */}
        <div style={{ display: "flex", flexDirection: "column", alignItems: "center", gap: 14, marginBottom: 40, zIndex: 1 }}>
          <div style={{ width: 56, height: 56, borderRadius: 14, background: "linear-gradient(135deg, #3B82F6, #6366F1)", display: "flex", alignItems: "center", justifyContent: "center", boxShadow: "0 0 32px rgba(59,130,246,0.35)" }}>
            <svg width="26" height="26" viewBox="0 0 24 24" fill="none" stroke="white" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round">
              <polyline points="16 18 22 12 16 6" />
              <polyline points="8 6 2 12 8 18" />
            </svg>
          </div>
          <div style={{ textAlign: "center" }}>
            <p style={{ margin: 0, fontSize: 18, fontWeight: 800, letterSpacing: "-0.03em", background: "linear-gradient(90deg, #E2E8F0, #94A3B8)", WebkitBackgroundClip: "text", WebkitTextFillColor: "transparent" }}>
              CodeCouncil
            </p>
            <p style={{ margin: "4px 0 0", fontSize: 11, color: "#4B5563", letterSpacing: "0.06em", textTransform: "uppercase", fontWeight: 500 }}>
              Auto Documentation
            </p>
          </div>
        </div>

        {/* Session badge */}
        {fromHackathon && (
          <div style={{ display: "flex", alignItems: "center", gap: 6, padding: "6px 14px", borderRadius: 100, background: "rgba(16,185,129,0.1)", border: "1px solid rgba(16,185,129,0.3)", fontSize: 11, fontWeight: 600, color: "#10B981", marginBottom: 28, zIndex: 1 }}>
            <svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5"><polyline points="20 6 9 17 4 12" /></svg>
            Session imported
          </div>
        )}

        {/* File info */}
        <div style={{ width: "100%", background: "rgba(19,19,30,0.8)", border: "1px solid #1E1E2E", borderRadius: 10, padding: "14px 16px", marginBottom: 20, zIndex: 1 }}>
          <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 10 }}>
            <span style={{ fontSize: 10, fontWeight: 700, color: "#F0DB4F", background: "#2A2700", border: "1px solid #3D3800", borderRadius: 3, padding: "1px 4px" }}>JS</span>
            <span style={{ fontSize: 12, fontWeight: 600, color: "#C8D6F0" }}>authController.js</span>
          </div>
          <div style={{ display: "flex", flexDirection: "column", gap: 4 }}>
            {[
              { label: "Snapshots", value: "5" },
              { label: "Contributors", value: "3" },
              { label: "Bugs fixed", value: "1" },
            ].map((r) => (
              <div key={r.label} style={{ display: "flex", justifyContent: "space-between" }}>
                <span style={{ fontSize: 11, color: "#4B5563" }}>{r.label}</span>
                <span style={{ fontSize: 11, fontWeight: 600, color: "#8892A4" }}>{r.value}</span>
              </div>
            ))}
          </div>
        </div>

        {/* Timeline mini list */}
        <div style={{ width: "100%", zIndex: 1 }}>
          <p style={{ margin: "0 0 8px", fontSize: 10, fontWeight: 600, letterSpacing: "0.07em", color: "#2E3550", textTransform: "uppercase" }}>Session timeline</p>
          <div style={{ display: "flex", flexDirection: "column", gap: 5 }}>
            {SNAPSHOTS_INFO.map((s) => (
              <div key={s.label} style={{ display: "flex", alignItems: "center", gap: 8 }}>
                <div style={{ width: 6, height: 6, borderRadius: "50%", background: s.color, flexShrink: 0, boxShadow: `0 0 4px ${s.color}88` }} />
                <span style={{ fontSize: 11, color: "#4B5563", flex: 1 }}>{s.label}</span>
                <span style={{ fontSize: 10, color: "#2E3550", fontFamily: "monospace" }}>{s.time}</span>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* ── RIGHT: Doc generator panel ── */}
      <div style={{ flex: 1, display: "flex", flexDirection: "column", background: "#0A0A0F", overflow: "hidden" }}>

        {/* Panel header */}
        <div style={{ padding: "24px 28px 0", flexShrink: 0 }}>
          <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 4 }}>
            <h1 style={{ margin: 0, fontSize: 20, fontWeight: 700, color: "#E2E8F0", letterSpacing: "-0.02em" }}>
              Documentation Generator
            </h1>
            <button
              id="btn-generate-docs"
              onClick={handleGenerate}
              disabled={generating}
              style={{
                display: "inline-flex", alignItems: "center", gap: 8, padding: "9px 18px",
                borderRadius: 9, border: "none", cursor: generating ? "not-allowed" : "pointer",
                background: generating ? "#1E1E2E" : "linear-gradient(135deg, #3B82F6, #6366F1)",
                color: generating ? "#64748B" : "white",
                fontSize: 13, fontWeight: 600,
                boxShadow: generating ? "none" : "0 4px 16px rgba(59,130,246,0.3)",
                transition: "all 0.2s", flexShrink: 0,
              }}
            >
              {generating ? (
                <>
                  <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" style={{ animation: "spin 1s linear infinite" }}>
                    <path d="M21 12a9 9 0 1 1-6.219-8.56" />
                  </svg>
                  Generating…
                </>
              ) : (
                <>
                  <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round">
                    <path d="M12 2L2 7l10 5 10-5-10-5z" /><path d="M2 17l10 5 10-5" /><path d="M2 12l10 5 10-5" />
                  </svg>
                  {readme ? "Regenerate" : "Generate Documentation"}
                </>
              )}
            </button>
          </div>
          <p style={{ margin: "0 0 20px", fontSize: 13, color: "#4B5563" }}>
            AI-powered README from your debug session. Click Generate to begin.
          </p>
          <div style={{ borderTop: "1px solid #1E1E2E" }} />
        </div>

        {/* Output area — scrollable */}
        <div style={{ flex: 1, overflowY: "auto", padding: "20px 28px 32px" }}>

          {/* Empty state */}
          {!readme && !generating && (
            <div style={{ display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", height: "100%", textAlign: "center", gap: 12 }}>
              <div style={{ width: 52, height: 52, borderRadius: 14, background: "rgba(59,130,246,0.06)", border: "1px dashed rgba(59,130,246,0.2)", display: "flex", alignItems: "center", justifyContent: "center" }}>
                <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="#3B82F6" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round">
                  <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" />
                  <polyline points="14 2 14 8 20 8" />
                  <line x1="16" y1="13" x2="8" y2="13" /><line x1="16" y1="17" x2="8" y2="17" />
                </svg>
              </div>
              <div>
                <p style={{ margin: "0 0 4px", fontSize: 14, fontWeight: 600, color: "#4B5563" }}>No documentation yet</p>
                <p style={{ margin: 0, fontSize: 12, color: "#2E3550" }}>Click "Generate Documentation" above to create your README</p>
              </div>
            </div>
          )}

          {/* Spinner */}
          {generating && (
            <div style={{ display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", height: "100%", gap: 14 }}>
              <svg width="36" height="36" viewBox="0 0 24 24" fill="none" stroke="#3B82F6" strokeWidth="2" strokeLinecap="round" style={{ animation: "spin 1s linear infinite" }}>
                <path d="M21 12a9 9 0 1 1-6.219-8.56" />
              </svg>
              <p style={{ margin: 0, fontSize: 13, color: "#4B5563" }}>Analysing session and generating documentation…</p>
            </div>
          )}

          {/* Generated output */}
          {readme && (
            <div style={{ background: "#12121A", border: "1px solid #1E1E2E", borderRadius: 12, overflow: "hidden" }}>
              {/* Toolbar */}
              <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", padding: "10px 16px", borderBottom: "1px solid #1E1E2E", background: "#0D0D18" }}>
                <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
                  <div style={{ width: 8, height: 8, borderRadius: "50%", background: "#10B981", boxShadow: "0 0 6px #10B981" }} />
                  <span style={{ fontSize: 12, fontWeight: 600, color: "#10B981" }}>README.md</span>
                  <span style={{ fontSize: 11, color: "#2E3550", marginLeft: 2 }}>· preview</span>
                </div>
                <div style={{ display: "flex", gap: 8 }}>
                  {/* Copy */}
                  <button
                    id="btn-copy-docs"
                    onClick={handleCopy}
                    style={{ display: "inline-flex", alignItems: "center", gap: 5, padding: "5px 12px", borderRadius: 6, border: "1px solid #2D2D3F", background: copied ? "rgba(16,185,129,0.1)" : "transparent", color: copied ? "#10B981" : "#8892A4", fontSize: 12, fontWeight: 500, cursor: "pointer", transition: "all 0.15s" }}
                  >
                    {copied ? (
                      <><svg width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5"><polyline points="20 6 9 17 4 12" /></svg>Copied!</>
                    ) : (
                      <><svg width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><rect x="9" y="9" width="13" height="13" rx="2" ry="2" /><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1" /></svg>Copy</>
                    )}
                  </button>
                  {/* Export */}
                  <button
                    id="btn-export-docs"
                    onClick={handleExport}
                    style={{ display: "inline-flex", alignItems: "center", gap: 5, padding: "5px 12px", borderRadius: 6, border: "none", background: "linear-gradient(135deg, #3B82F6, #6366F1)", color: "white", fontSize: 12, fontWeight: 600, cursor: "pointer" }}
                  >
                    <svg width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round">
                      <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" /><polyline points="7 10 12 15 17 10" /><line x1="12" y1="15" x2="12" y2="3" />
                    </svg>
                    Export .md
                  </button>
                </div>
              </div>
              {/* Content */}
              <div style={{ padding: "20px 24px" }}>
                <pre style={{ margin: 0, fontFamily: "'JetBrains Mono','Cascadia Code',monospace", fontSize: 12.5, color: "#CBD5E1", lineHeight: 1.75, whiteSpace: "pre-wrap", wordBreak: "break-word" }}>
                  {readme}
                </pre>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

// ── Page export ────────────────────────────────────────────────────────────
export default function DocPage() {
  return (
    <div style={{ height: "100vh", display: "flex", flexDirection: "column", background: "#0A0A0F", fontFamily: "var(--font-geist-sans), system-ui, sans-serif" }}>
      <Navbar />
      <Suspense fallback={
        <div style={{ flex: 1, display: "flex", alignItems: "center", justifyContent: "center" }}>
          <span style={{ color: "#4B5563", fontSize: 14 }}>Loading…</span>
        </div>
      }>
        <DocPageInner />
      </Suspense>
      <style>{`@keyframes spin { from { transform: rotate(0deg); } to { transform: rotate(360deg); } }`}</style>
    </div>
  );
}
